### ISSUE TITLE
Thx alot

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#10]
just need to say Thx for this program i needed this so bad with my reading probes and dyslexia , i was wondering if u have a forum or a place where we can talk about this program and suggest new option i would like to see a delay option before it starts to talk.

**Comment by raykai** [comment]
im all so wandering if there could be a way to get the add-on menu button to be free on screen not stuck on the social button as im using an other UI "ElvUI" and we don't have a social button on this UI

**Comment by EJocys** [comment]
Thank you. I will try to add these options. I will post message here when it is done.

**Comment by VJocys** [comment]
<p>Quick fix...<br />
 If “Social-Friends” button is not visible:<br />
1. Open <i>JocysCom-TextToSpeech-WoW.xml</i> file with Notepad.<br />
2. Find and change <code>"FriendsMicroButton"</code> to <code>"UIParent"</code><br />
3. Reload WoW. -- [■] (Stop) button should appear at the top-center of your screen. You can unlock [■] (Stop) button in [≡] (Options) and move it to desired position.</p>

<p><sub>Usual file directory:<br /> C:\Program Files\World of Warcraft\Interface\AddOns\JocysCom-TextToSpeech-WoW\JocysCom-TextToSpeech-WoW.xml</sub></p>

**Comment by raykai** [comment]
thx for the fast fix :) now just missing a delay option before it starts to talk

**Comment by VJocys** [comment]
Silence (ms) before and after speech option in [Options] tab of “Monitor” 2.2.42 (2015-11-17) was added.

**Comment by raykai** [comment]
any news on if we will be getting:  Getting value if NPC has voice over for all text... in order not to start TTS speech ?

**Comment by raykai** [comment]
thx alot :)
