### ISSUE TITLE
adon error when chating with realID

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#11]
i get the error every time i talk in chat using real ID or Freands list or if some one from my list talks to me 

Date: 2015-10-14 22:44:32
ID: 2
Error occured in: Global
Count: 1
Message: SendChatMessage(): Invalid escape code in chat message
Debug:
   [C]: ?
   [C]: ?
   [C]: SendChatMessage()
   Misspelled\Misspelled.lua:275:
      Misspelled\Misspelled.lua:272
   (tail call): ?
   ...ysCom-TextToSpeech-WoW\JocysCom-TextToSpeech-WoW.lua:416: JocysCom_SpeakMessage()
   ...ysCom-TextToSpeech-WoW\JocysCom-TextToSpeech-WoW.lua:284:
      ...ysCom-TextToSpeech-WoW\JocysCom-TextToSpeech-WoW.lua:141
   [C]: BNSendWhisper()
   ..\FrameXML\ChatFrame.lua:4124: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4147:
      ..\FrameXML\ChatFrame.lua:4143
   [C]: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
   [C]: ?
Locals:

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  AchievementsReminder, v
  AskMrRobot, v28
  Atlas, v1.32.00
  AtlasDungeonLocs, v1.32.00
  AutoLog, vv6.2.0.0
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v5.21e.5566 (SanctimoniousSwamprat)
  BetterAddonList, vr21
  BittensSpellFlashAtonement, v60000.1.0
  BittensSpellFlashPriest, v60100.201503092107
  BlizzMove, vv1.4
  bosseskilled, v1.4.2
  Configator, v5.1.DEV.382(/embedded)
  CTLibrary, v6.0.2.2
  CTViewport, v6.0.2.0
  DBMArchaeology, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMInterrupts, v6.2.0
  DBMRaidLeadTools, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v8.34
  ElvUIChannelAlerts, v3.09
  ElvUIConfig, v1.02
  ElvUICustomTweaks, v1.21
  ElvUIDTBars2, v6.2.0.0007
  ElvUIEnhanced, v3.1.0-beta5
  ElvUILocPlus, v2.10
  ELvUILootOptions, v6.0.3b
  GarrisonCommanderBroker, v2.7.7 6.2.2
  GatherMate2, v1.35.4
  GTFO, v4.37.4
  GuildMemberOnline, v1.1 
  HandyNotes, vv1.4.5
  HandyNotesGuild, v1.8
  HealersHaveToDie, v2.3.7
  Informant, v5.21e.5566 (SanctimoniousSwamprat)
  JocysComTextToSpeechWoW, v6.2.0
  KibsItemLevel, vv0.7.5
  LFRAdvanced, v6.2.2.20444
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibSharedMedia30, v3.0-93
  LootAppraiser, v0.93 BETA
  Mapster, v1.6.4
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFramesDark, v3.1.0
  MinimapButtonFrameSkinPack, v3.0.1b
  Misspelled, v1.6.1
  MogIt, v3.5.5
  MogItAccessories, v
  MoveAnything, v15.2.4
  Overachiever, v0.83
  Postal, v3.5.4
  RaidAchieveFilter, v1.8.3
  RaidAchievement, v
  RaidAchievementOldModules, v
  RaidSlackCheck, v1.49
  Reloadui, v1.0
  Scrap, v12.24
  ScrapSpotlight, v12.24
  Skada, v1.4-32
  SlideBar, v5.21e.5566 (SanctimoniousSwamprat)
  Sounds4Chat, vv6.1.1
  SpeedyLoad, v2.2.1
  SpellFlash, v6.24.1
  SpellFlashCore, v2.1.1
  SPTimers, v3.1.9
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TidyPlates, v6.16.1-6-g70b083d
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.389(/embedded)
  TipTac, v15.07.02
  TipTacItemRef, v15.07.02
  TipTacTalents, v15.07.02
  TomTom, vv60200-2.0.0
  TradeSkillMaster, v3X195
  TradeSkillMasterAccounting, v3X29
  TradeSkillMasterAppHelper, v3X3
  TradeSkillMasterAuctionDB, v3X7
  TradeSkillMasterAuctioning, v3X82
  TradeSkillMasterCrafting, v3X89
  TradeSkillMasterDestroying, v3X24
  TradeSkillMasterShopping, v3X65
  TradeSkillMasterVendoring, v3X45
  TradeSkillMasterWarehousing, v3X13
  TradeSkillMasterWoWuction, v3X5
  VuhDo, v3.70
  VuhDoOptions, v3.70
  WoWQuestTextReader, v
  ZygorGuidesViewer, v5.0
  BlizRuntimeLib_enUS v6.2.2.60200 <none>
  (ck=a8f)

**Comment by raykai** [comment]
do you think it can get fixed ?

**Comment by VJocys** [comment]
Please, try new WoW Addon version 2.2.46 (2015-11-14). Did it fix the problem?

**Comment by raykai** [comment]
yes it did fix it thx 1000 :)
