### ISSUE TITLE
just wandering if...

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#13]
im just wandering if it would be hard to add the: Getting value if NPC has voice over for all text... in order not to start TTS speech ?

**Comment by VJocys** [comment]
At this moment I have no idea, how to extract required information about audio file, assigned to NPC (if file exists, if it is set to play and its length). When / if I will figure this out, I will try to add such feature to “Addon” and “Monitor” :).

**Comment by raykai** [comment]
you could ask this question on : 
http://forums.curseforge.com
you could even pout this add-on in curse would be nice and add a link to dl the monitor if u cant post a exe file you would need to ask a mod there tho.
