### ISSUE TITLE
Text not detected by monitor

### ISSUE THREAD

**Issue by Quezako** [JocysCom/TextToSpeech#18]
Hello,

I've really tried to make WoW text 2 speech work but it doesn't.
The addon sends the messages in my wisper chat, but it is not detected by the monitor.
if I monitor the clipboard and copy the text, it is detected.

So, I guess it is a network or port problem?
I use the french version of WoW 64 bits, I've also tried with 32 bits version
under Windows 10 pro.

Thanks in advance for your help, don't hesitate if you need me to do some testing.

**Comment by raykai** [comment]
its work well for me thats wired.
is the addon on in wow ?

**Comment by Quezako** [comment]
Yes, the addon is on. I've said: "The addon sends the messages in my wisper chat, but it is not detected by the monitor.".
It may be a network configuration error. By the past, I have tested several VPN on my computer, but I've disabled all unused adapters.

**Comment by VJocys** [comment]
You can try latest Monitor version 2.4.6 (2016-11-15). TCP/IPv6 support added. Also, there are some other changes, related to network. Maybe, everything will work this time.

**Comment by Quezako** [comment]
Ok, great! I'll play WoW extensively during mid-December. I will surely give it a try!

**Comment by Quezako** [comment]
It works! Thanks a lot!
