### ISSUE TITLE
dose not read quest that start with <

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#19]
its not reading quest that starts with < 

like :

<Khadgar's voice erupts from the elemental ones again>

Obtaining information on the Pillars of Creation before the Legion could stop us was a considerable victory. It won't bring back those we lost on the Broken Shore, but I believe it will help us avenge them.

Dalaran has become a focal point of the Legion's assault. Your presence here is crucial. If the demons are putting this much effort into attacking the city, it means Dalaran will play a pivotal role in the struggle to save Azeroth.

it will not rad any of it as it has <> in the quest text

**Comment by VJocys** [comment]
Noted. If such problem still exists in new version of Addon, I will try to recreate it in conversation with some NPC and fix it.
