### ISSUE TITLE
wired bug Monitor stops reading after 10 mins of use

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#20]
i have this wired bug that after say 10 mins my text to speech Monitor 2.3.6 stops reading and i need to close  it and reopen it for it to work ones more till i hit 10-20 mins using default voices. ruining on win 10.

**Comment by VJocys** [comment]
You can try version 2.4.6 (2016-11-15). Also, Monitor can't play voices, if their trial period is expired. You can test, which ones are expired, by enabling one voice at a time and pressing [ Speak ] button in Monitor. Such voices must be disabled in [ Voices ] tab.

**Comment by raykai** [comment]
im not using the trial for voices :P  il try with version 2.4.6 il let you know if it works
