### ISSUE TITLE
Does this work for WotLK version?

### ISSUE THREAD

**Issue by emanueljuandavid** [JocysCom/TextToSpeech#21]
I am running the private server Dalaran, I tried the beta version and it did not read any text. It did work for the "real game" meaning blizzards servers. 

I get the button above the social friends buttons in game and I checked all the boxes which reset upon relog every time and didn't work anyway.

Help please?

**Comment by EJocys** [comment]
We are supporting official WoW and WoW Classic only. This is because we are not playing WoW anymore and other projects takes all free time.
