### ISSUE TITLE
How to install voices to the monitor program?

### ISSUE THREAD

**Issue by emanueljuandavid** [JocysCom/TextToSpeech#22]
I have no idea how to, and nothing said anything about it in the installation guide.

**Comment by VJocys** [comment]
Paragraph "5. Install additional text-to-speech voices, if needed." on pages...
http://www.jocys.com/Software#Text_to_Speech
https://github.com/JocysCom/TextToSpeech
...describes, where you can get TTS Voices for your Windows operating system.
