### ISSUE TITLE
bug for the ones with out Social-Friends button 

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#28]
since the last release i modified the file JocysCom-TextToSpeech-WoW.xml
and change "QuickJoinToastButton" to "UIParent" as i always do but now my button is stuck on the far left side of the screen it used to reset at the top center of screen now it seams to just popup where the normal Social-Friends is on the normal UI and i cant see the menu to unlock it to movie it.

if i hover or click on the [≡] button there is no menu opening

**Comment by raykai** [comment]
im useing the UI elvui http://www.tukui.org/dl.php it would be nice as i always need to edit this file for ech new release.

**Comment by raykai** [comment]
it seams that after pouting back the normal wow UI i could unlock the button then move it then tern on my UI elvui  then it was working.... i all so removed all JocysCom SavedVariables from my WTF folders.

**Comment by VJocys** [comment]
Thank you. "Addon" updated to version 2.2.88 (2016-12-18). From now, parent of mini-frame ([≡][■]) is WoW's "UIParent" frame. After this update, mini frame ([≡][■]) should be visible in "elvui" and similar addons. At first, mini frame ([≡][■]) will appear at the center of the screen. Also, mini frame is unlocked (for movement) by default.

To move mini frame with [≡][■] buttons:
1. Click on [≡] (Options) button, to open “Options” window.
2. Unlock mini frame by unchecking first check-box in “Options” window.
3. Move mini frame, wherever you like.
4. Lock it again, by checking the same check-box.

**Comment by raykai** [comment]
has the DL link bine updated ? still says: 
Jocys.com Text to Speech Monitor 2.4.18 (2016-12-14) • Digitally Signed
Jocys.com Text to Speech “World of Warcraft” Addon 2.2.86 (2016-12-14)

on README.MD page of github...

**Comment by VJocys** [comment]
Yes, download file was new. Updated README.MD file. Thank you.
