### ISSUE TITLE
monitor bug word be sean as blood elf....

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#29]
Evry time there is the word be in quests text the monitor reports/reads be as blood elf...

<voice required="name=Microsoft David Desktop">
  <volume level="100">
    <rate absspeed="2">
      <pitch absmiddle="0">The disguise **blood elf** complete! </pitch>
    </rate>
  </volume>
</voice>

it should be: The disguise be complete!

<voice required="name=Microsoft David Desktop">
  <volume level="100">
    <rate absspeed="2">
      <pitch absmiddle="0">Though I have a feeling I'll blood elf needin a priest to get this stench out once we're gone. </pitch>
    </rate>
  </volume>
</voice>

should be: Though I have a feeling I'll **be** needin a priest to get this stench out once we're gone. 

![capture](https://cloud.githubusercontent.com/assets/8138894/21341507/d7ee1534-c65a-11e6-844d-7be296858fda.JPG)

![capture2](https://cloud.githubusercontent.com/assets/8138894/21341444/8ae7c172-c65a-11e6-8414-004ca49ae75d.JPG)

http://www.wowhead.com/quest=38347/stealth-by-seaweed

I have this bug with all quest since the last 2 versions or so.

**Comment by raykai** [comment]
i see in the Acronyms tab there is **KEY** be **Value** blood elf 

im thinking this is where its messing up.

**Comment by VJocys** [comment]
Disabled acronym "be" > "blood elf" in Monitor 2.4.18 (2016-12-20) by default. Thank you.
