### ISSUE TITLE
my stop button dont seam to be working.

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#30]
i press the stop button (in-game addon) but it keeps on talking...

i get this lua error when pressing the stop button:

43x ...ysCom-TextToSpeech-WoW\JocysCom-TextToSpeech-WoW-7.3.0.lua:782: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
...ysCom-TextToSpeech-WoW\JocysCom-TextToSpeech-WoW-7.3.0.lua:782: in function `JocysCom_StopButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = "igMainMenuOptionCheckBoxOn"

![y6jzgq7vtta8rxyermaasw](https://user-images.githubusercontent.com/8138894/33251668-7c16d6ec-d306-11e7-8f2e-e11cf569e261.jpeg)

i also cant drag the 2 buttons (option, stop) even tho they are unlocked in the options.

**Comment by VJocys** [comment]
In new WoW Addon version I changed:

PlaySound("igMainMenuOptionCheckBoxOn");
to...
PlaySound(856); 

As for locked mini-frame with [Options] and [Stop] buttons: can you try to drag mini-frame by clicking on dark background around the buttons. It is always there (fully transparent). It becomes visible, when "Options" window is open.

I added sentence "Grab frame by clicking on dark background around buttons." to checkbox description.

**Comment by raykai** [comment]
ty
