### ISSUE TITLE
can we have a way to tern off all Acronyms

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#33]
I'm looking for a fast way to turn off all the Acronyms that is in the Monitor. having a switch off this option would be nice. as clicking them one by one in the list to turn them all off is a pain...

**Comment by VJocys** [comment]
Text to Speech Monitor updates:
2.4.22 (2018-01-22) -- Search now includes "Group" column in [Acronyms] tab.
2.4.21 (2018-01-22) -- [Select All], [Deselect All], [Check Selected], [Uncheck Selected] buttons added in [Acronyms] tab.

**Comment by raykai** [comment]
ty :)
