### ISSUE TITLE
Not working in patch 8.0 (BfA)

### ISSUE THREAD

**Issue by Quezako** [JocysCom/TextToSpeech#35]
Hello,

The addon is not working in version 8.0.
The main window appears, but only the background, not the texts.
When opening a dialog, nothing happens.
Also, I can't see any lua error, which it strange.

**Comment by Quezako** [comment]
Oh thanks, I did not see that! Great news!
I'll try it right now, I'm pretty sure it will work. :)

**Comment by Quezako** [comment]
Ha, the link has been removed, so the problem is still here.
I did not have time to download the test version.

**Comment by scottmartin** [comment]
It looks like they updated the other links to point to the new version of the addon. I just tried to download it from the main links on their site and it seems to be working in game.

**Comment by Quezako** [comment]
Ah yes, it is working now.
It is strange because the zip file is the same that the one I used few days ago. Maybe the problem was from my WoW files or something else.
Thanks!

**Comment by scottmartin** [comment]
Not sure, but I was originally seeing the same problem you were. So I don't think it was just your instance of WoW.
