### ISSUE TITLE
App volume preference not saved

### ISSUE THREAD

**Issue by Quezako** [JocysCom/TextToSpeech#36]
Hello, the TTS app sound volume is too loud and I can't manage to save the volume in app nor in the Windows sound preferences.
Is there a way to save TTS app default volume, like in user.config file or something ?

**Comment by scottmartin** [comment]
I too wish the app would remember my volume setting. It's the first thing I have to set every single time I open it.

**Comment by EJocys** [comment]
This issue was fixed in new release of the TTS Monitor.
