### ISSUE TITLE
Not working with latest version.

### ISSUE THREAD

**Issue by CelerityStudios** [JocysCom/TextToSpeech#37]
Hi, I have used the TextToSpeech in the past without issue but coming back to WoW even with the latest version of the software it doesn't seem to be able to read the packages sent from WoW.
The monitor say it has picked up the process and the package count is going up, I have also check in WoW and the addon is sending the message in chat. I have tested the monitor with its build in tool and it picks it up fine just not from WoW it would seem.

Kind Regards.

**Comment by EJocys** [comment]
It seems like WoW started to encrypt messages after last major patch. It is good for security, but Text-To-Speech Monitor stopped working, because it can't recognise messages and therefore turn them into speech.

**Comment by Mirellanmawl** [comment]
So will there ever be a Text-To-Speech Monitor and WoW Addon for the current version of World of Warcraft?

**Comment by EJocys** [comment]
We figured out how to pass text-to-speech data from WoW Addon to TTS Monitor. We are using display pixels as data buffer now :). New version TTS Monitor and WoW Addon works with WoW and WoW Classic. You can download latest version from: https://github.com/JocysCom/TextToSpeech
