### ISSUE TITLE
Only a small part of the text is read

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JocysCom/TextToSpeech#4]
```
What is the expected output? What do you see instead?

Only partial text is spoken, sometimes just one word. The full message shows in 
the monitor, but only a part is spoken.


What version of the product are you using? On what operating system?

2.2.12 on windows 7 sp1


Please provide any additional information below.

Screenshots attached. One shows the full message incomming. But the SAPI XML 
text only has part of the message, and this is all that is read to the user.


```

Original issue reported on code.google.com by `nno...@gmail.com` on 14 Mar 2015 at 10:13

Attachments:
* [q.png](https://storage.googleapis.com/google-code-attachments/jocyscom-wow-texttospeech/issue-4/comment-0/q.png)
* [w.png](https://storage.googleapis.com/google-code-attachments/jocyscom-wow-texttospeech/issue-4/comment-0/w.png)

**Comment by VJocys** [comment]
Is problem fixed with new version of “Addon” and “Monitor”?
