### ISSUE TITLE
Pre-patch 16 October 2020

### ISSUE THREAD

**Issue by wobbo** [JocysCom/TextToSpeech#43]
Only the chat is still working. I made a couple of screenshots. Let me know what I can do to help you. I think you for all your time! 

![Pre-patch  2](https://user-images.githubusercontent.com/12646389/96307271-a7bb1700-1001-11eb-9ff3-247d93227d43.png)
![Pre-patch  3](https://user-images.githubusercontent.com/12646389/96307273-a853ad80-1001-11eb-81ba-5ff8afa72e6a.png)
![Pre-patch  4](https://user-images.githubusercontent.com/12646389/96307274-a8ec4400-1001-11eb-9862-11564ccb7fa2.png)
![Pre-patch  1](https://user-images.githubusercontent.com/12646389/96307276-a8ec4400-1001-11eb-966e-bf1e8ac21cb0.png)

**Comment by VJocys** [comment]
Thank you for reporting problems.

Solution:

I updated WoW Addon version to 9.0.1 (2020-20-16):

LUA: "GetGossipText()" replaced with "C_GossipInfo.GetText()".
XML: Frame with "edgeFile" removed.
TOC: Interface and Version updated to 90001 and 9.0.1

I hope, this will fix main issues.

**Comment by wobbo** [comment]
I downloaden [JocysCom-TextToSpeech-WoW.zip](https://github.com/JocysCom/TextToSpeech/blob/master/TextToSpeech/WoW/JocysCom-TextToSpeech-WoW.zip) _https://github.com/JocysCom/TextToSpeech/blob/master/TextToSpeech/WoW/JocysCom-TextToSpeech-WoW.zip_

I still have the same problem.

**Comment by wobbo** [comment]
Is there a key binding option?

**Comment by VJocys** [comment]
Can you paste in WoW chat window this message-text to show detailed errors?

/console scriptErrors 1

To hide errors again:

/console scriptErrors 0

**Comment by wobbo** [comment]
Suddenly it works...

**Comment by wobbo** [comment]
Do you still need scriptErrors?

**Comment by VJocys** [comment]
Good to hear it works again. Thank you for all help. No, I don't need srciptErrors, unless something stops working :).

**Comment by wobbo** [comment]
I am very relieved that it works. I'm glad we got the pre-patch and not the new extension. Now I am prepared! I need this to understand the new story. Thanks.
