### ISSUE TITLE
Main default voise 

### ISSUE THREAD

**Issue by wobbo** [JocysCom/TextToSpeech#44]
I have been looking in  _Voice Default_ to change the voice of the quest in the _Map & Quests Log_. Is there a name for that? 

In the XML I see that _Map & Quest Log_ do not have a _name_. Is there a way to do that?

**Comment by wobbo** [comment]
In the program _Voice Default_ I added one named "Quest Log". 
`Quest Log | Female | Humanoid | -1 | -1 | 100 | en-EN | IVONA 2 Amy OEM `

In the document _JocysCom-TextToSpeech-WoW.lua_  line number 365 I added `name = "Quest Log"`.

**Comment by VJocys** [comment]
Thank you for helpful idea. I was not able to extract character name from "Map & Quest Log" frame. Ability to assign specific name in Monitor's [Voice Defaults] tab using `"Quest Log"` name is very useful. I added `name = "Quest Log"` line to latest WoW Addon version 9.0.1.3 (2020-10-23).
