### ISSUE TITLE
Chat [Party Leader] no TTS

### ISSUE THREAD

**Issue by wobbo** [JocysCom/TextToSpeech#45]
I can hear the whole Party Members except for the Party Leader.

**Comment by VJocys** [comment]
Thank you for reporting the problem. Added missing lines for party leader "CHAT_MSG_PARTY_LEADER" event in LUA file:
```
name = JocysCom_RemoveRealmName(playerName)
sex = select(5, GetPlayerInfoByGUID(guid))
```
I hope, this will fix the issue.

**Comment by wobbo** [comment]
I see! It's the only one missing that. I haven't tried it yet but it seems to solve the problem.

**Comment by wobbo** [comment]
Problem solved!
