### ISSUE TITLE
Can't make TTS to work with ShadowLands

### ISSUE THREAD

**Issue by Quezako** [JocysCom/TextToSpeech#47]
Hello,

Like for every new extension, I tried to make TTS work and failed. 😅
I don't know what I'm doing wrong, but nothing is played.

I've activated the monitor: display and I see the pixels in-game, but the XML doesn't seem to change in the monitoring app.
![Screenshot (80)](https://user-images.githubusercontent.com/98868/99880360-7a3b3c00-2c45-11eb-918d-c0f2c80e7b35.png)

**Comment by VJocys** [comment]
Hi,

Pixel line colours are distorted in WoW screenshot - TTS Monitor can't find pixel line.

TTS Monitor searches for colours (red, green, blue): #220000,#002200,#000022...
Distorted colours in WoW screenshot (red, green, blue): #290000,#002900,#000029...

Make sure, that video card colour settings like brightness, contrast, gamma, etc. do not distort colours.

https://www.jocys.com/TTS/#Video_Card_Problems

**Comment by Quezako** [comment]
Well, I don't get it, I did everything as mentionned, bu I still get red 41 instead of red 34.
I really don't get where I've made a mistake.

![Screenshot (82)](https://user-images.githubusercontent.com/98868/100290841-dcca6a00-2fae-11eb-90c6-393a0bb374b1.png)
![Screenshot (83)](https://user-images.githubusercontent.com/98868/100290849-dfc55a80-2fae-11eb-81fb-5ef28af6792e.png)
![Screenshot (84)](https://user-images.githubusercontent.com/98868/100290850-e05df100-2fae-11eb-9d46-ded09869770c.png)
![Screenshot (86)](https://user-images.githubusercontent.com/98868/100290851-e0f68780-2fae-11eb-9893-fcf7c92bc868.png)
![Screenshot (87)](https://user-images.githubusercontent.com/98868/100290853-e18f1e00-2fae-11eb-9afc-3af48285f89f.png)

**Comment by VJocys** [comment]
Hi,

You can also check WoW Game ► Game Menu ► System ► Graphics ► Advanced ► Contrast, Brightness and Gamma settings...

![image](https://user-images.githubusercontent.com/11961339/100295373-5b101780-2f81-11eb-86d6-8af9d80e9538.png)

**Comment by Quezako** [comment]
Oh yes, you are right, my gamma was on 1.1.
This is probably due to that, but I can't check until the server patch is done.
I will keep you updated.

**Comment by Quezako** [comment]
I confirm, it was because of gamma in WoW.
Thanks for the quick support!

**Comment by VJocys** [comment]
Thank you for reporting the problem. I added information about WoW game’s colour settings to TTS page’s “Help” section.

https://www.jocys.com/TTS/#WoW_Game_Resolution_and_Colour_Settings
