### ISSUE TITLE
TBC Classic

### ISSUE THREAD

**Issue by GtoxNow** [JocysCom/TextToSpeech#50]
The ingame addon is currently not working with TBC Classic, sadly. Hoping this is somthing you can get fixed, was looking forward to playing the story with text to speech. Looks like it is not picking up quest text, the whole addon options screen is "blank". Addon still picks up NPC info and sends to program.
![TTS addon](https://user-images.githubusercontent.com/84622320/119223272-b2d6a800-baf8-11eb-8c00-c2ddb2f14c02.png)

**Comment by viktorblack** [comment]
same but i don't think it will get a update

**Comment by GtoxNow** [comment]
yeah, saldy looks like there is no response or updating of the addon now :( was looking forward to TBC and listen to all the quests for story.

**Comment by GtoxNow** [comment]
Hmm, somehow I got it to work... :) Hope it helps somone, would like feedback if it worked or not for others.

1: Open the Joycscom-TextToSpeech-WoW.lua file with notepad.
2: Change debug to true: local DebugEnabled = true
3: change local classic into this: local classic = (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)

Then ingame addon showed as normal I and just had to put check marks on things same as it have in retail.

Should look like this from the top and down in lua file:
`-- Extract current TOC Version (Interface) in chat window: /run print((select(4, GetBuildInfo())));
-- Show errors (1) or hide errors (0): /console scriptErrors 1
-- Show or hide frame names: /fstack
-- Show events: /eventtrace
-- Blizzard > Settings > Game Settings > Game Name > [v] Additional command line arguments > [-console] > WoW Game > "`" > [exportInterfaceFiles code] or [exportInterfaceFiles art]

-- #:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\ACCOUNTNAME\SavedVariables.lua - Blizzard's saved variables.
-- #:\Program Files (x86)\World of Warcraft\_retail_WTF\Account\ACCOUNTNAME\SavedVariables\JocysCom-TextToSpeech-WoW.lua - Per-account settings for each individual AddOn.
-- #:\Program Files (x86)\World of Warcraft\_retail_WTF\Account\ACCOUNTNAME\RealmName\CharacterName\JocysCom-TextToSpeech-WoW.lua - Per-character settings for each individual AddOn.

-- Debug mode true(enabled) or false(disabled).
local DebugEnabled = true

-- version, build, date, tocversion = GetBuildInfo()
local version, build, date, tocversion = GetBuildInfo()
local classic = (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)
`

**Comment by viktorblack** [comment]
thank you it works for me

**Comment by VJocys** [comment]
GtoxNow, thank you for suggestion. WoW Addon ▸ JocysCom-TextToSpeech-WoW.lua ▸ Line 16...

Old WoW Addon version 9.0.5.1 (2021-04-09):
`local classic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC)`

New WoW Addon version 9.0.5.2 (2021-06-04):
`local classic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC or WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)`

I don't play WoW anymore... hope it will fix the problem.
