### ISSUE TITLE
Jocys TextToSpeech addon blocks scrolling to zoom in and out

### ISSUE THREAD

**Issue by ryankhart** [JocysCom/TextToSpeech#53]
I'm having an issue with this addon even with no other addons activated. Whenever I scroll anywhere on the screen except for the very outer edge, it does not work to zoom my camera in and out, but it does on the edges. And when I open up the options window for this addon, it covers nearly the entire screen with this overlay, and I don't know what I did to make this happen. When I first opened the options window it didn't show this. I didn't test out scrolling to zoom at that time though. Is it possible that this is a bug that was introduced with the Dragonflight pre-patch that this addon needs an update for?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3673962/200146861-7d93732b-f750-4fac-9b20-b50b483dae4e.png">

**Comment by ryankhart** [comment]
That's weird. It just resolved itself after I started playing again. It seems to be an intermittent issue so far. I'll update here if I learn more.

**Comment by ryankhart** [comment]
Ok, the issue did come back after a while, but then it resolves it self as soon as I speak with an NPC with a quest window like in this screenshot.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3673962/200148651-b1c2226f-241a-4911-a9bc-85d9721b5947.png">

**Comment by ryankhart** [comment]
Actually, I could not consistently fix the issue by talking to NPCs with quests. I have no idea now.

**Comment by vadviktor** [comment]
I'm having the same issue, and all I can see is a number being incremented right next to this addon's buttons. I have no idea what that is :/ The reading works, though, so it should be a "small" bug because of the UI upgrade.

**Comment by ryankhart** [comment]
Ok so, I got motivated enough to peruse through the lua script code, and I discovered a way to effectively disable the scrolling feature altogether, albeit in a very hacky way by setting the scrollFrame from the top left to the top left, so it's basically 1 pixel.

Here's my modified addon repackaged up in a zip file for anyone who doesn't mind playing without the scroll feature.
[JocysCom-TextToSpeech-WoW.zip](https://github.com/JocysCom/TextToSpeech/files/10026663/JocysCom-TextToSpeech-WoW.zip)

**Comment by ryankhart** [comment]
Here's an updated version because there was still a small area in the top left corner where it wouldn't let me scroll for other game functions, so after reading the code and understanding slightly more, I just commented out everything after `JocysCom_DialogueScrollFrame:ClearAllPoints()`, which seems to work better than my previous version.
[JocysCom-TextToSpeech-WoW.zip](https://github.com/JocysCom/TextToSpeech/files/10062414/JocysCom-TextToSpeech-WoW.zip)

**Comment by vadviktor** [comment]
Thank you for all your efforts @ryankhart 🙏 
While I do not yet have the time to play yet to test this out, I have one small improvement to suggest: Could you rather make a fork and link that into the thread, please?
That way, you don't distribute "questionable" zip files (I know you don't, but still), and also we can see the changes more clearly. From that fork, we can still download your code and use it 😉

**Comment by ryankhart** [comment]
> That way, you don't distribute "questionable" zip files

Oh that's fair. I usually do that kind of thing, but since I saw this as a temporary hack, I didn't think it was worth the effort to use git and set up a streamlined development environment.

I just forked it and uploaded my changed file through the GitHub web interface.

Here are my changes:
https://github.com/ryankhart/TextToSpeech/commit/99d635f88855e87947874ef19252c563a67c0c93

**Comment by VJocys** [comment]
Thank you 

> I'm having an issue with this addon even with no other addons activated. Whenever I scroll anywhere on the screen except for the very outer edge, it does not work to zoom my camera in and out, but it does on the edges. And when I open up the options window for this addon, it covers nearly the entire screen with this overlay, and I don't know what I did to make this happen. When I first opened the options window it didn't show this. I didn't test out scrolling to zoom at that time though. Is it possible that this is a bug that was introduced with the Dragonflight pre-patch that this addon needs an update for?

Thank you for reporting the problem. I replaced old `GossipGreetingScrollFrame` with new `GossipFrameInset` as parent frame for `JocysCom_DialogueScrollFrame` in JocysCom-TextToSpeech-WoW.lua file. I hope, WoW Addon version 10.0.2.1 (2022-11-22) will work now.
