### ISSUE TITLE
Text playing twice and overlapping 

### ISSUE THREAD

**Issue by jakolas6** [JocysCom/TextToSpeech#8]
When I speak to an NPC the TTS begins to read the text as expected. After around 10 seconds of speech the TTS restarts the dialog. My incoming messages tab shows that it is receiving each command twice. So it will read through the first part of the text twice and then proceed to read the second part of the quest twice. When TTS has completed the entire quest text. It begins again from the top and re-reads the quest in it's overlapping style. NPC chat is also duplicated and read twice. 

please help I would love to have this working correctly

**Comment by VJocys** [comment]
1. Can you check, which version of Monitor and WoW Addon do you use? Latest version is 2.2.28 (2015-04-30).
2. If you use some chat or interface related addons, can you try to disable them temporary and then check, if problem remains or disappears?

**Comment by jakolas6** [comment]
Yes the montitor is up to date (I only downloaded it on the day i comented above) and i tried disabling all other addons and running TTS but had the same problem. :(

**Comment by VJocys** [comment]
Please, try new Monitor version 2.2.30 (2015-05-03). Did it fix the problem?

**Comment by jakolas6** [comment]
No, still having the same problem. 
![new](https://cloud.githubusercontent.com/assets/12195111/7447746/1272d184-f25b-11e4-9632-b82da069deac.jpg)

**Comment by VJocys** [comment]
Please, try new Monitor version 2.2.31 (2015-05-05). Did it fix the problem with duplicates?

**Comment by jakolas6** [comment]
Yes! Duplicates have stopped and the dialog is not beginning again after completing the full text. Thank you this is fantastic!
