### ISSUE TITLE
Jocys.com Text to Speech Monitor and WoW Addon Error

### ISSUE THREAD

**Issue by auxic2501** [JocysCom/TextToSpeech#9]
In addition to the error below I have to restart the exe every 5 min or so because the tts stops working.

Date: 2015-07-31 00:23:37
ID: 1
Error occured in: Global
Count: 1
Message: [string "JocysCom_OptionsFrame:OnShow"] line 1:
   attempt to call global 'JocysCom_OptionsFrame_OnShow' (a nil value)
Debug:
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
Locals:
self = JocysCom_OptionsFrame {
 0 = <userdata>
 TitleText = <unnamed> {
 }
 RightBorder = <unnamed> {
 }
 LeftBorder = <unnamed> {
 }
 TitleBg = <unnamed> {
 }
 BottomBorder = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 BotRightCorner = <unnamed> {
 }
 TopBorder = <unnamed> {
 }
 CloseButton = <unnamed> {
 }
 BotLeftCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 Bg = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call global 'JocysCom_OptionsFrame_OnShow' (a nil value)"

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  ActionBarSaver, v
  ArkInventory, v30511
  ArkInventoryRules, v10001
  AucAdvanced, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21e.5566.5459(5.21e/embedded)
  AucMatchUndercut, v5.21e.5566.5507(5.21e/embedded)
  AucStatHistogram, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatSales, v5.21e.5566.5476(5.21e/embedded)
  AucStatSimple, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21e.5566.5323(5.21e/embedded)
  AucUtilAHWindowControl, v5.21e.5566.5347(5.21e/embedded)
  AucUtilAppraiser, v5.21e.5566.5545(5.21e/embedded)
  AucUtilAskPrice, v5.21e.5566.5447(5.21e/embedded)
  AucUtilAutoMagic, v5.21e.5566.5537(5.21e/embedded)
  AucUtilCompactUI, v5.21e.5566.5550(5.21e/embedded)
  AucUtilEasyBuyout, v5.21e.5566.5507(5.21e/embedded)
  AucUtilFixAH, v5.21e.5566 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21e.5566.5417(5.21e/embedded)
  AucUtilPriceLevel, v5.21e.5566.5535(5.21e/embedded)
  AucUtilScanButton, v5.21e.5566.5403(5.21e/embedded)
  AucUtilScanFinish, v5.21e.5566.5515(5.21e/embedded)
  AucUtilScanProgress, v5.21e.5566.4979(5.21e/embedded)
  AucUtilScanStart, v5.21e.5566.5347(5.21e/embedded)
  AucUtilSearchUI, v5.21e.5566.5556(5.21e/embedded)
  AucUtilSimpleAuction, v5.21e.5566.5531(5.21e/embedded)
  AucUtilVendMarkup, v5.21e.5566.4828(5.21e/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.6.10
  BeanCounter, v5.21e.5566 (SanctimoniousSwamprat)
  Configator, v5.1.DEV.382(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21e.5566 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21e.5566 (SanctimoniousSwamprat)
  HealBot, v6.2.0.0
  HealersHaveToDie, v2.3.6
  JocysComTextToSpeechWoW, v6.1.0
  LibExtraTip, v5.12.DEV.390(/embedded)
  SlideBar, v5.21e.5566 (SanctimoniousSwamprat)
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  BlizRuntimeLib_enUS v6.2.0.60200 <none>
  (ck=867)

**Comment by VJocys** [comment]
Which version of WoW are you using?
Extract current version in chat window: /run print((select(4, GetBuildInfo())));
Addon doesn't support old WoW versions.

**Comment by auxic2501** [comment]
When I put that in chat the game responds with "60200"

On the log in screen it shows "version 6.2.0 (20338) (Release x64) July 27
2015"

**Comment by VJocys** [comment]
Please, try new Addon version 2.2.43 (2015-08-02). Did it fix the problem? If not, maybe you can tell, when error in Addon appears (do you click on button, start dialogue, etc., ...).

**Comment by auxic2501** [comment]
I tried updating with the files available from (
http://www.jocys.com/Software).  The problem is still there.  The error
shows up when i first log in to the character.  It shows up again every
time I use /reload.  The error does not show up at any other time.  It
occurs with no other plugins loaded.  I'm not sure if it's related to the
TTS not working every now and then.  I fix this problem by reloading
"JocysCom.TextToSpeech.Monitor.exe"

Thanks for your support.

**Comment by VJocys** [comment]
Please, try new Addon version 2.2.45 (2015-08-05). Did it fix the problem?

**Comment by auxic2501** [comment]
Yes the problem appears to have been fixed. :)  Thank you so much!!
